#!/bin/sh

# vim: noai:ts=4:sw=4:expandtab
#Otto-PKG - Ein Paketmanager, der Pakete über BitTorrent herunterlädt.

#:BSD 2-Clause License

#Copyright (c) 2019-2020, Luiz Antônio Rangel von Projeto Pindorama
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are met:
#
#1. Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#2. Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#Dependências:
#Python 3.{4 or 8}
#Libtorrent and Libtorrent bindings for Python 3.x
#CURL
#POSIX 7-Zip (p7zip)

#TO DO:
#Terminar as funções pelo menos.
#Portar para outros sistemas UNIX caso for necessário.
#Otimizar o máximo possível.

##############################################
#"Settar" algumas variáveis para uma execução "perfeita"  do Otto:
##Exportar as duas variaveis de linguagem como "C" (inglês), para maior performance e velocidade do script. Por isso, acentos não serão usados no output do programa.
export LANG=C
export LC_ALL=C

##Especificações do Otto no código do Otto:
export PROG='Otto'
export VER='0.3-alpha'
export PKG_FORMT='.otpm'
export PKG_COMPSS='7z'
export HOST_OS=$(uname)
#^Dica para os outros desenvolvedores: para variáveis simples como essas, exceto pela última onde estou puxando um subshell, usem sempre aspas simples.
#O motivo eu possivelmente explicarei na documentação, se não alguém o explicará... mas se resume em velocidade na execução.

##Definir cores.
export RED='\033[31;1m'
export YELLOW='\033[33;1m'
export BLUE='\033[34;1m'
export GREEN='\033[32;1m'
export END='\033[m'

#Aspas simples não devem ser usadas aqui em diante com o printf, o que sera explicado na documentacao.
#Carregar biblioteca de variáveis externas, do sistema e do usuário
#configuradas já na instalação do sistema ou do Otto em si caso for possível:
if [[ -f $OTTOETC/make.cfg ]]; then
	source $OTTOETC/make.cfg
else
	printf "${RED}make.cfg nao foi encontrado$END\n"
fi
############## FUNÇÕES DO SCRIPT ##############

function chkroot(){
if [[ $EUID -ne 0 ]]; then
	printf "${RED}Login wie root user.$END\n"
	exit 1
fi
}

function pkgdown(){
for torrent in $@; do
	#Estou sem muita certeza do que realmente quero nessa parte...
	#Velocidade:
	#pkgnm=$(printf "$torrent\n" | cut -d "/" -f 2)
	#...ou desempenho:
	pkgnm=$(cut -d '/' -f 2 <<< $(printf "$torrent\n"))
	curl $MIRROR/packages/$torrent.otlnk -O /tmp/$pkgnm.torrent
	sh -c 'python3.8 otto-torrent.py -s -f /tmp/$pkgnm.torrent -d $SRCDIR'
done
}

#estou enrolando muito para fazer tudo, eu sei.
function install(){
    chkroot
    printf "${RED}Erro:$END funcao ainda nao implementada.\n"
    exit 1
}
function remove(){
    chkroot
    printf "${RED}Erro:$END funcao ainda nao implementada.\n"
    exit 1
}
function update(){
    chkroot
    printf "${RED}Erro:$END funcao ainda nao implementada.\n"
    exit 1
}
function mkpkg(){
    printf "${RED}Erro:$END funcao ainda nao implementada.\n"
    exit 1
}

function info(){
    printf "Otto Paketmanager version: $VER\n"
    printf "Betriebssystem: $HOST_OS\n"
    printf "Paketformat: $PKG_FORMT\n"
    printf "\
Copyright (c) 2019-2020 Luiz Antonio Rangel von Project Pindorama.
Copyright (c) 2020 Caio Novais von Project Pindorama.
"
exit 0
}

function help(){ 
printf "\
${GREEN}Otto $VER, ein paketmanager.$END

> help    - Mostrar essa mensagem de ajuda, para mais informacao leia o manual.
> info    - Listar informacoes do programa.
> dig     - Instalar pacote.
> bury    - Remover pacote.
> up2date - Atualizar index do repositorio e pacotes.
> mkpkg   - Criar pacotes.
"
exit 0
}
############## FIM DAS FUNCOES ################

############## CASE DO SCRIPT #################
case $1 in
	help*) help "$2" ;;
	info*) info "$2" ;;
	dig*) install "$2" ;;
	bury*) remove "$2" ;;
	up2date*) update "$2" ;;
	*) help "$2" ;;
esac
###############################################
